config/routes.rb
Rails.application.routes.draw do

  #root to landing page for the app
  root 'cards#index'

  #devise user routes
  devise_for :users

  #routes for main functions of the application
  resources :cards

  #stripe payment routes
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  #user personal account route
  get "/account/", to: "users#account"

  #configure routes for messenger
  resources :conversations do
    resources :messages
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  validates :title, :condition, :manufacturer, :price, :picture,
  :team_id, :season_id, presence: true
  
  validates :price, numericality: { greater_than: 0 }
  
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User', optional: true
  has_one :season  
  has_one :team
  has_one_attached :picture

  enum condition: {graded: 0, brand_new: 1, like_new: 2, used: 3, n_specified: 4}
  enum manufacturer: {upper_deck: 0, panini: 1, topps: 2, other: 3,}


end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: "User"
  belongs_to :recipient, foreign_key: :recipient_id, class_name: "User"

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :recipient_id

  # This scope validation takes the sender_id and recipient_id for the conversation and checks whether 
  # a conversation exists between the two ids because we only want two users to have one conversation.

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id = ?)
     OR (conversations.sender_id = ? AND conversations.recipient_id = ?)",
    sender_id, recipient_id, recipient_id, sender_id)
  end

  def receiver(current_user)
    self.sender_id == current_user.id ? self.recipient : self.sender
  end

  def unread_message_count(current_user)
    self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :seller, class_name: 'User'
    belongs_to :buyer, class_name: 'User'
    belongs_to :card
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
end

app/models/season.rb
class Season < ApplicationRecord
    has_many :cards
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable #:trackable

  validates :username, :email, presence: true, uniqueness: { case_sensitive: false }
  validates :first_name, :last_name, presence: true, length: { maximum: 50, 
    too_long: "%{count} characters is the maximum allowed" } 

  # has_many :ratings
  has_many :cards, dependent: :destroy, foreign_key: :seller_id
  has_many :orders

  has_many :sales, class_name: 'Order', foreign_key: :seller_id
  has_many :purchases, class_name: 'Order', foreign_key: :buyer_id
  has_many :sold_cards, through: :sales, source: :card
  has_many :purchased_cards, through: :purchases, source: :card
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :set_card, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only:[:new, :update, :edit, :destroy]

    def index
        @q = Card.ransack(params[:q])
        @cards = @q.result.with_attached_picture.paginate(:page => params[:page], :per_page=>12)

    end

    def create
        @card = current_user.cards.build(card_params)
        # @card = Card.new(card_params)
        # @card.save
       
        if @card.save
            redirect_to @card
        else
            @card.errors.full_messages
            @seasons = Season.all
            @teams = Team.all
            render 'new'
        end
    end

    def new
        @card = Card.new
        @seasons = Season.all
        @teams = Team.all
        @manufacturers = Card.manufacturers.keys 
        @condition = Card.conditions.keys
    end

    def edit
    end

    def update

        if @card.update(card_params)
            redirect_to @card
        else
            render 'edit'
        end

    end

    def show

        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.try(:email),
            line_items: [{
                name: @card.title,
                # images: @card.picture,
                amount: (@card.price * 100).to_i,
                currency: 'usd',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    card_id: @card.id,
                    user_id: current_user.try(:id),
                    seller_id: @card.seller.id
                }
            },
            success_url: "#{root_url}payments/success?cardId=#{@card.id}",
            cancel_url: "#{root_url}"
        )

        @session_id = session.id
        
    end

    def destroy
        @card.destroy

        redirect_to cards_path
    end

    private

        def set_card
            # @card = Card.includes(:seller, picture_attachment: :blob).find(params[:id])
            @card = Card.includes(:seller).with_attached_picture.find(params[:id])
    
            @seasons = Season.all
            @teams = Team.all
            @manufacturers = Card.manufacturers.keys 
            @condition = Card.conditions.keys
        end

        def card_params
            params.require(:card).permit(:title, :description, :condition, 
                :season_id, :manufacturer, :price, :picture, :team_id, :seller_id,
                :purchased)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @conversation.messages.where("user_id != ? AND read = ?", current_user.id, false).update_all(read: true)
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user = current_user

    if @message.errors.any?
      render "index"
    elsif @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private
    def message_params
      params.require(:message).permit(:body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def account
        @cards = current_user.cards.with_attached_picture.paginate(:page => params[:page], :per_page=>8)
    end

    def update
        @user = current_user

        if @user.update(current_user_params)
            redirect_to @user
        else
            render 'edit'
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def get_unread_messages(current_user)
        conversations = Conversation.where(sender: current_user) + Conversation.where(recipient: current_user)
        unread_messages = Message.where("user_id != ? AND read = ?", current_user.id, false).where(conversation_id: [conversations]).count

    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_search_form.html.erb
<form class="form-inline my-2 my-lg-0 s-form float-right">

<div>
  <%= sort_link(@q, :price, 'Price', default_order: :desc) %>
  <%= sort_link(@q, :created_at, 'Newest', default_order: :desc) %>
</div>

<%= search_form_for @q do |f| %>

  <%= f.label ""%>
  <%= f.search_field :title_or_description_cont, class: "form-control mr-sm-2" %>

  <%= f.submit 'Search', class: "btn btn-outline-success my-2 my-sm-0" %>
  <%= link_to "Reset Search", cards_path, class: "btn btn-outline-warning" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Harcourt Collectors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render  "shared/navbar" %>
    <%= render  "shared/devise_error" %>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/shared/_devise_error.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
    // <% if flash[:success] %>
    //   var $toastContent = $('<span><%= flash[:success] %></span>');
    //   toastr.success($toastContent)
    // <% end %>
    // <% if flash[:info] %>
    //   var $toastContent = $('<span><%= flash[:info] %></span>');
    //   toastr.info($toastContent)
    // <% end %>
    // <% if flash[:warning] %>
    //   var $toastContent = $('<span><%= flash[:warning] %></span>');
    //   toastr.warning($toastContent)
    // <% end %>
    // <% if flash[:danger] %>
    //   var $toastContent = $('<span><%= flash[:danger] %></span>');
    //   toastr.error($toastContent)
    // <% end %>
  <% flash.each do |key, value| %>
    <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
    toastr['<%= type %>']('<%= value %>');
  <% end %>
</script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light nav">
      <%= link_to image_tag('logo.svg', :class => 'navbar-brand logo'), cards_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-stretch" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to 'Cards', cards_path, class: "nav-link" %>
          
            <%= link_to 'Sell', new_card_path, class: "nav-link" %> 
          
          <% if user_signed_in? %>
            <%= link_to 'Account', account_path, class: "nav-link" %>
            <%= link_to 'Logout', destroy_user_session_path, 
          method: :delete, class: "nav-link" %>
          <% else %>
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %> 
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          <%end%>
          </div>
          <div class="navbar-nav ml-auto">
            <% if user_signed_in? %>
                <% if get_unread_messages(current_user) != 0 %>
                  <%= link_to 'Inbox', conversations_path, class: "nav-link float-right justify-content-end btn-warning" %>
                <% else %>
                  <%= link_to 'Inbox', conversations_path, class: "nav-link float-right justify-content-end" %>  
                 <%end%>
            <%end%>
          </div>
        </div>
      </div>
 </nav>