config/routes.rb
Rails.application.routes.draw do

  #root to landing page for the app
  root 'cards#index'

  #devise user routes
  devise_for :users

  #routes for main functions of the application
  resources :cards

  #stripe payment routes
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  #user personal account route
  get "/account/", to: "users#account"

  #configure routes for messenger
  resources :conversations do
    resources :messages
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def webhook
        payment_id = params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(payment_id)

        card_id = payment.metadata.card_id
        buyer_id = payment.metadata.user_id
        seller_id = payment.metadata.seller_id
        
        card = Card.find(card_id)

        card.purchased = true
        card.buyer_id = buyer_id
        card.save
        
        order = Order.create(buyer: buyer_id, card_id: card_id, seller_id: seller_id)
        order.save
    end


    def success                
        
    end
        

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/success.html.erb
<p>Congratulations you are the proud owner of a new basketball card<p>

<div class="container-fluid">
  <h1 class="hero-title text-center m-5">Congratulations you are the proud owner of a new basketball card</h5>
</div>

<div class="jumbotron jumbotron-fluid bg-light">
  <div class="container">
    <h1 class="display-4 text-center p-2">You purchased A card</h1>
        <div class="display-4 text-center p-2">
            
        </div>
    
   </div>
</div>


<%= link_to "Browser Cards", cards_path %>