config/routes.rb
Rails.application.routes.draw do

  #root to landing page for the app
  root 'cards#index'

  #devise user routes
  devise_for :users

  #routes for main functions of the application
  resources :cards

  #stripe payment routes
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  #user personal account route
  get "/account/", to: "users#account"

  #configure routes for messenger
  resources :conversations do
    resources :messages
  end


end

app/models/card.rb
class Card < ApplicationRecord

  validates :title, :condition, :manufacturer, :price, :picture,
  :team_id, :season_id, presence: true
  
  validates :price, numericality: { greater_than: 0 }
  
  belongs_to :seller, class_name: 'User'
  belongs_to :buyer, class_name: 'User', optional: true
  has_one :season  
  has_one :team
  has_one_attached :picture

  enum condition: {graded: 0, brand_new: 1, like_new: 2, used: 3, n_specified: 4}
  enum manufacturer: {upper_deck: 0, panini: 1, topps: 2, other: 3,}


end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :set_card, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only:[:new, :update, :edit, :destroy]

    def index
        @q = Card.ransack(params[:q])
        @cards = @q.result.with_attached_picture.paginate(:page => params[:page], :per_page=>12)

    end

    def create
        @card = current_user.cards.build(card_params)
        # @card = Card.new(card_params)
        # @card.save
       
        if @card.save
            redirect_to @card
        else
            @card.errors.full_messages
            @seasons = Season.all
            @teams = Team.all
            render 'new'
        end
    end

    def new
        @card = Card.new
        @seasons = Season.all
        @teams = Team.all
        @manufacturers = Card.manufacturers.keys 
        @condition = Card.conditions.keys
    end

    def edit
    end

    def update

        if @card.update(card_params)
            redirect_to @card
        else
            render 'edit'
        end

    end

    def show

        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user.try(:email),
            line_items: [{
                name: @card.title,
                # images: @card.picture,
                amount: (@card.price * 100).to_i,
                currency: 'usd',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    card_id: @card.id,
                    user_id: current_user.try(:id),
                    seller_id: @card.seller.id
                }
            },
            success_url: "#{root_url}payments/success?cardId=#{@card.id}",
            cancel_url: "#{root_url}"
        )

        @session_id = session.id
        
    end

    def destroy
        @card.destroy

        redirect_to cards_path
    end

    private

        def set_card
            # @card = Card.includes(:seller, picture_attachment: :blob).find(params[:id])
            @card = Card.includes(:seller).with_attached_picture.find(params[:id])
    
            @seasons = Season.all
            @teams = Team.all
            @manufacturers = Card.manufacturers.keys 
            @condition = Card.conditions.keys
        end

        def card_params
            params.require(:card).permit(:title, :description, :condition, 
                :season_id, :manufacturer, :price, :picture, :team_id, :seller_id,
                :purchased)
        end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with scope: @card, url: cards_path, local: true do |form| %>
        <% if @card.errors.any? %>
            <div class="form_error">
                <ul>
                    <% @card.errors.full_messages.each do |msg| %>
                        <li><%='Error: ' +  msg %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>

    <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control"  %>
    </div>

    <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control"%>
    </div>

    <div class="form-group">
        <%= form.label :price %>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">$</span>
            </div>
            <%= form.number_field :price, step: 0.01, class: "form-control" %>
        </div>
        
    </div>

    <div class="form-row">

        <div class="form-group col-md-6">
            <%= form.label :condition %>
            <%= form.select(:condition, [['Graded', 'graded'], ['Brand New', 'brand_new'], ['Like New', 'like_new'], ['Used', 'used'], ['Not specified', 'not_specified']], {}, { class: "custom-select" })  %>
        </div>

        <div class="form-group col-md-6">
            <%= form.label :manufacturer %>
            <%= form.select(:manufacturer, [['Upper Deck', 'upper_deck'], ['Panini', 'panini'], ['Topps', 'topps'], ['Other', 'other']], {}, { class: "custom-select" } ) %>
        </div>
    </div>

    <div class="form-row">
        
        <div class="form-group col-md-6">
            <%= form.label :season_id %>
            <%= form.select(:season_id, @seasons.map{ |s| [s.years, s.id] }, {}, { class: "custom-select" })  %>
        </div>

        <div class="form-group col-md-6">
            <%= form.label :team_id %>
            <%= form.select(:team_id, @teams.order(team: :asc).map{ |t| [t.team, t.id] }, {}, { class: "custom-select" }) %>
        </div>
    
    </div>

    <% form.hidden_field :seller_id, value: current_user.id %>

    <div class="custom-file">
        <%= form.label :picture, class: "custom-file-label" %>
        <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg', placeholder: "Choose Picture", class: "custom-file-input btn btn-outline-secondary" %>
    </div>

    <br><br>
    
    <div class="form-group">
        <%= form.submit "Sell Card", class: "btn btn-primary"%>
    </div>

    <% end %>



    

app/views/cards/edit.html.erb
<div class="sell-container">
    <div class="sell-form">
        <h3 class="heading">Edit Card Listing</h3>

        <%= render 'form' %>
    </div>
</div>

app/views/cards/index.html.erb
<div class="container">
    <%= render "layouts/search_form"%>
</div>

<div class="index">
    <h1 class="page-header text-center ">Hardcourt Collectors</h1>
    
        <!--Grid row setup for cards -->
                <div class="row">
                    <% @cards.each do |card| %>
                        <% if !card.purchased %>
                        <!--Grid column setup for cards -->
                            <div class="col-md-4 mb-4 d-flex align-items-stretch">
                                <div class="card listing border-right border-bottom">
                                    <%= link_to (image_tag(card.picture, :class => 'card-img-top') if card.picture.attached?), card_path(card.id) %> 
                                    <div class="card-body">
                                        <h5 class="card-title"><%= card.title %></h5>
                                        <p class="card-price"><%= number_to_currency(card.price) %></p>
                                        <%= link_to 'View Card', card_path(card.id), class: "btn btn-primary" %>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                </div>
            
        <%= will_paginate @cards %>
    </div>
</div>

app/views/cards/new.html.erb
<div class="sell-container">
    <div class="sell-form">
        <h3 class="heading">Sell a Card</h3>

        <%= render 'form' %>
    </div>
</div>

app/views/cards/show.html.erb
<section class="container card-show">
    <div class="row mt-10">
        <div class='col-md-8 mt-5'>
            <div class="bg-light text-dark">
                <h2 class=""><%= @card.title %></h2>
            
        
                <span class="content">
                    <%= image_tag(@card.picture) if @card.picture.attached? %>
                </span>

                <div>

                    <h3 class="">Description</h3>
                    <%= @card.description %>  


                    <h3>Product Details</h3>
                    <table class="table bg-light">            
                        <tr>
                            <td class="font-weight-bold">Condition:</td>
                            <td class=""><%=@card.condition.capitalize%></td>
                        </tr>

                        <tr>
                            <td class=" font-weight-bold">Manufacturer:</td>
                            <td class=""><%=@card.manufacturer.capitalize%></td>
                        </tr>

                        <tr>
                            <td class=" font-weight-bold">Season:</td>
                            <td class=""><%=@card.season_id%></td>
                        </tr>

                        <tr>
                            <td class=" font-weight-bold">Team:</td>
                            <td class=""><%=@card.team_id%></td>
                        </tr>
                    </table>
                
                </div>
            </div>
        </div>
        
        <div class="col-md-4 mt-5">
            <h4 class="text-center"><%= number_to_currency(@card.price) %></h4>
            <p class="text-center">Sold by <%= @card.seller.username %></p>

            <div class="row">
                <div class="col">
                <% if user_signed_in? %>
                    <button data-stripe="payment" class="btn btn-primary">Buy Now</button>
                    <script src="https://js.stripe.com/v3/"></script>
                <% else %>
                    <%= button_to 'Buy Now', new_user_session_path, class: 'btn btn-primary'  %>
                <% end %>
                </div>
                
                
                <% if user_signed_in? && current_user.id == @card.seller.id %>
                    <div class="col">
                        <%= link_to 'Edit Card', edit_card_path(@card), class: "btn btn-warning" %>
                    </div>
                    <div class="col">
                        <%= button_to 'Delete Listing', card_path(@card),
                            method: :delete, class: "btn btn-danger",
                            data: { confirm: 'Are you sure?' } %>
                    </div>
                <% else %>
                    <%= button_to "Message #{@card.seller.username}", conversations_path(sender_id: current_user, recipient_id: @card.seller.id), method: "post", class: "btn btn-success" %>
                <% end %>
            </div>
            
        </div>
    </div>
</section>

<script>
    document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
        const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
        stripe.redirectToCheckout({
            sessionId: "<%= @session_id %>"
        });
    });
</script>